---
title: "Fortune 500 Map"
author: "Sarah McDonald"
date: "6/16/2020"
output: md_document
always_allow_html: true
---
Data:
```{r}
library(dplyr)
library(tidycensus)
library(leaflet)
library(sf)
library(readr)
wac <- read.csv("/sfs/qumulo/qhome/tp2sk/Git/dspg20fairfax/data/original/va_wac_S000_JT00_2017.csv", colClasses = c("w_geocode" = "factor"))

va_xwalk <- read.csv("/sfs/qumulo/qhome/tp2sk/Git/dspg20fairfax/data/original/va_xwalk.csv",  colClasses = c("tabblk2010" = "factor", "trct" = "factor"))

fairfax_wac <- merge(wac, va_xwalk[va_xwalk$cty == 51059, c("tabblk2010","cty", "trct", "bgrp")], by.x = "w_geocode", by.y = "tabblk2010")

# Note: C000 = total number of jobs
fairfax_trct <- fairfax_wac %>% select(w_geocode, cty, trct, bgrp, C000) %>% group_by(trct) %>% summarize(totaljobs = sum(C000),perTotalJobs = (totaljobs/sum(fairfax_wac$C000))*100)
```


Get ACS shapefiles
```{r, warning = F, message = F, results = 'hide'}
data_fairfax <-   get_acs(geography = "tract",
          variables = "B00001_001",
          state = "VA",
          county = 059, 
          geometry = TRUE)

data_fairfax_final <- merge(data_fairfax, fairfax_trct, by.x= "GEOID", by.y = "trct", all = TRUE)

data_fairfax_final <- st_transform(data_fairfax_final, 4326)

# Write
write_rds(data_fairfax_final, "/sfs/qumulo/qhome/tp2sk/Git/dspg20fairfax/data/lodes/lodes_spatial.Rds")

```


```{r}
fortune_geo <- read_sf("/sfs/qumulo/qhome/sm9dv/dspg20fairfax/data/fortune/fortune_1000/fairfax_fortune_1000_geo.shp")
```


```{r}

pal <- colorQuantile("Oranges", domain = data_fairfax_final$perTotalJobs, probs = seq(0, 1, length = 10), right = FALSE)

leaflet(data = data_fairfax_final,options = leafletOptions(minZoom = 10))%>%
  addTiles() %>%
  addPolygons(fillColor = ~pal(perTotalJobs),fillOpacity = .8, stroke = FALSE) %>%
  addMarkers(data = fortune_geo, popup = fortune_geo$Name) %>%
  addLegend("bottomleft", 
            pal = pal, 
            values =  ~perTotalJobs,
            title = "Percent of All<br> Fairfax County Jobs,<br> by Decile Group", 
            opacity = 1,
            labFormat = function(type = "quantile", cuts = 10, p = perTotalJobs) {
                    n = length(cuts)
                    paste0("[", round(cuts[-n], 3), " &ndash; ", round(cuts[-1], 3), ")")
                  })
  


```


```{r}
knitr::kable(quantile(data_fairfax_final$perTotalJobs, prob = seq(0, 1, length = 10), type = 5), col.names = "")
  

boxplot(data_fairfax_final$perTotalJobs)
```


