---
title: "Fairfax County 2020 Summer Project"
output: html_document
---

```{css, echo=FALSE}
/* this chunnk of code centers all of the headings */
h1, h2, h3 {
  text-align: center;
}
```

### Project Overview 

This project will explore labor markets in Fairfax County, VA to better understand the landscape and barriers to economic opportunity for the county’s residents, businesses, and places. With particular attention to post-COVID socioeconomic circumstances, the team will use local, state, and federal data sources to (1) provide Census tract-level characterization of the Fairfax County workforce, occupation sectors, and industry composition; (2) explore how this landscape may change post-pandemic and identify areas that are or have the potential to create emerging businesses/new industries; (3) map workforce flows within and in/out of Fairfax County by select employment factors and explore scenarios of post-pandemic change in workforce flows. The project findings can inform Fairfax County COVID response and provide insights into workforce readiness, economic vibrancy, and industry diversification, contributing to the county’s strategic plan goal of improving economic opportunity in the area.

### Project Goals 

This project will allow our sponsor to better understand the landscape and barriers to economic opportunity for the county’s residents, businesses, and places, one of the goals of Fairfax County’s strategic plan. In light of the current pandemic, it will allow the county to identify the current characteristics of its resident and commuting labor force, the characteristics of its businesses and industries, the geographic and temporal flows between them, and how this landscape may change after covid. These insights can help shape post-pandemic employment, transportation, and housing policy and program development, as well as serve as a baseline for measuring future change across the county.

### Our Approach 

The project will (1) as background, review existing Fairfax County documents to understand the baseline labor force and industry state of the county, as well as current strategies in place to develop, attract, and retain employees and employers; (2) implement the Data Science Framework with emphasis on data discovery, screening, acquisition, fitness-for-use assessment, preparation, linkage, and exploration; (3) develop a tract-level characterization of Fairfax County labor markets, explore potential post-pandemic changes and identify emerging areas, map network flows and examine change scenarios, and visualize and interpret findings; (4) communicate findings to sponsor with a symposium presentation, poster, Sage methods brief, and other outputs.