---
title: "Network Maps"
author: "Sarah McDonald"
date: "7/10/2020"
output: html_document
---
```{r, echo = F, message = F, warning=F, results = 'hide'}
library(tidycensus)
library(leaflet)
library(sf)
library(shiny)


source("/sfs/qumulo/qhome/sm9dv/dspg20fairfax/src/09_network_descriptives/network_functions.R")

network_stats(vars = "SA01", years = 2014, types = types)

data_fairfax <-   get_acs(geography = "tract",
                          variables = "B00001_001",
                          state = "VA",
                          county = 059, 
                          geometry = TRUE)

for(type in types){
  nodelist <- get(paste("nodelist_2015_S000_", type, sep = ""))
  
  fairfax_data <- merge(data_fairfax[, c("GEOID", "geometry")], nodelist[, c("tract", "wtd_deg_cent_out", "wtd_deg_cent_in", "btw_cent", "eigen_cent")], by.x= "GEOID", by.y = "tract", all = TRUE)
  fairfax_data <- st_transform(fairfax_data, 4326)

  #pal <- colorQuantile("Blues",5,  domain = fairfax_data$wtd_deg_cent_out)

  #pal_in <- colorQuantile("Oranges",5, domain = fairfax_data$wtd_deg_cent_in)

  #pal_btw <- colorQuantile("Purples",5,  domain = fairfax_data$btw_cent)

  #pal_eigen <- colorQuantile("Greens",5,  domain = fairfax_data$eigen_cent)
  
  assign(paste("fairfax_2015_S000_", type, sep =  ""), fairfax_data)
  
}



fairfax_2015_S000_all <- merge(data_fairfax[, c("GEOID", "geometry")], nodelist_2015_S000_all[, c("tract", "wtd_deg_cent_out", "wtd_deg_cent_in", "btw_cent", "eigen_cent")], by.x= "GEOID", by.y = "tract", all = TRUE)

fairfax_2015_S000_all <- st_transform(fairfax_2015_S000_all, 4326)

```

# All jobs (top: indegree/outdegree, bottom: betweennness and eigenvector)

```{r, figures-side, fig.show="hold", out.width="50%", echo = F}


pal <- colorQuantile("Blues",5,  domain = fairfax_2015_S000_all$wtd_deg_cent_out)

pal_in <- colorQuantile("Oranges",5, domain = fairfax_2015_S000_all$wtd_deg_cent_in)

pal_btw <- colorQuantile("Purples",5,  domain = fairfax_2015_S000_all$btw_cent)

pal_eigen <- colorQuantile("Greens",5,  domain = fairfax_2015_S000_all$eigen_cent)


l1 <- leaflet(data = fairfax_2015_S000_all,options = leafletOptions(minZoom = 10))%>%
  addTiles("https://{s}.basemaps.cartocdn.com/rastertiles/voyager_labels_under/{z}/{x}/{y}.png") %>%
  addPolygons(fillColor = ~pal(wtd_deg_cent_out), fillOpacity = .8, stroke = FALSE) %>%
  addLegend("bottomleft", 
            pal = pal, 
            values =  ~wtd_deg_cent_out,
            title = "Weighted Degree Centrality: Out<br> By Quantile Group", 
            opacity = 1, 
            labFormat = function(type = "quantile", cuts = 10, p = wtd_deg_cent_out) {
              n = length(cuts)
              paste0("[", round(cuts[-n], 3), " &ndash; ", round(cuts[-1], 3), ")")
            })



l2 <- leaflet(data = fairfax_2015_S000_all,options = leafletOptions(minZoom = 10))%>%
  addTiles("https://{s}.basemaps.cartocdn.com/rastertiles/voyager_labels_under/{z}/{x}/{y}.png") %>%
  addPolygons(fillColor = ~pal_in(wtd_deg_cent_in), fillOpacity = .8, stroke = FALSE) %>%
  addLegend("bottomleft", 
            pal = pal_in, 
            values = ~wtd_deg_cent_in,
            title = "Weighted Degree Centrality: In<br> By Quantile Group", 
            opacity = 1,
            labFormat = function(type = "quantile", cuts = 10, p = wtd_deg_cent_in) {
              n = length(cuts)
              paste0("[", round(cuts[-n], 3), " &ndash; ", round(cuts[-1], 3), ")")
            })




l3 <- leaflet(data = fairfax_2015_S000_all,options = leafletOptions(minZoom = 10))%>%
  addTiles("https://{s}.basemaps.cartocdn.com/rastertiles/voyager_labels_under/{z}/{x}/{y}.png") %>%
  addPolygons(fillColor = ~pal_btw(btw_cent), fillOpacity = .8, stroke = FALSE) %>%
  addLegend("bottomleft", 
            pal = pal_btw, 
            values = ~btw_cent,
            title = "Betweenness Centrality<br> By Quantile Group", 
            opacity = 1, 
            labFormat = function(type = "quantile", cuts = 10, p = btw_cent) {
              n = length(cuts)
              paste0("[", round(cuts[-n], 3), " &ndash; ", round(cuts[-1], 3), ")")
            })


l4 <- leaflet(data = fairfax_2015_S000_all,options = leafletOptions(minZoom = 10))%>%
  addTiles("https://{s}.basemaps.cartocdn.com/rastertiles/voyager_labels_under/{z}/{x}/{y}.png") %>%
  addPolygons(fillColor = ~pal_eigen(eigen_cent), fillOpacity = .8, stroke = FALSE) %>%
  addLegend("bottomleft", 
            pal = pal_eigen, 
            values = ~eigen_cent,
            title = "Eigen Centrality<br> By Quantile Group", 
            opacity = 1, 
            labFormat = function(type = "quantile", cuts = 10, p = eigen_cent) {
              n = length(cuts)
              paste0("[", round(cuts[-n], 3), " &ndash; ", round(cuts[-1], 3), ")")
            })


fluidRow(column(6, l1), 
         column(6,l2))
fluidRow(column(6, l3), 
         column(6, l4))

cor(st_drop_geometry(fairfax_2015_S000_all[, -1]))

```





# federal jobs (top: indegree/outdegree, bottom: betweennness and eigenvector)

# private jobs (top: indegree/outdegree, bottom: betweennness and eigenvector)


