---
title: "Flows into Fairfax"
author: "Owen Hart"
date: "7/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

libraries
```{r}
library(dplyr)
library(ggplot2)
```


Reading in data tables
```{r}
jobs_all <- read.csv("/sfs/qumulo/qhome/sm9dv/dspg20fairfax/data/od/jobsall.csv")
jobs_fed <- read.csv("/sfs/qumulo/qhome/sm9dv/dspg20fairfax/data/od/jobs_federal.csv")
jobs_priv <- read.csv("/sfs/qumulo/qhome/sm9dv/dspg20fairfax/data/od/jobs_priv.csv")
```


Parsing GEOID into FIPS codes
```{r}
# First parsing residence GEOIDs (I assume h_geocode_tract is supposed to be r_geocode_tract)
jobs_all$r_state <- as.numeric(substr(jobs_all$h_geocode_tract, 1, 2))
jobs_all$r_county <- as.numeric(substr(jobs_all$h_geocode_tract, 3, 5)) #gets rid of leading 0
jobs_all$r_tract <- as.numeric(substr(jobs_all$h_geocode_tract, 6, 11))

jobs_fed$r_state <- as.numeric(substr(jobs_fed$h_geocode_tract, 1, 2))
jobs_fed$r_county <- as.numeric(substr(jobs_fed$h_geocode_tract, 3, 5)) #gets rid of leading 0
jobs_fed$r_tract <- as.numeric(substr(jobs_fed$h_geocode_tract, 6, 11))

jobs_priv$r_state <- as.numeric(substr(jobs_priv$h_geocode_tract, 1, 2))
jobs_priv$r_county <- as.numeric(substr(jobs_priv$h_geocode_tract, 3, 5)) #gets rid of leading 0
jobs_priv$r_tract <- as.numeric(substr(jobs_priv$h_geocode_tract, 6, 11))

# Now parsing workplace GEOIDs
jobs_all$w_state <- as.numeric(substr(jobs_all$w_geocode_tract, 1, 2))
jobs_all$w_county <- as.numeric(substr(jobs_all$w_geocode_tract, 3, 5)) #gets rid of leading 0
jobs_all$w_tract <- as.numeric(substr(jobs_all$w_geocode_tract, 6, 11))

jobs_fed$w_state <- as.numeric(substr(jobs_fed$w_geocode_tract, 1, 2))
jobs_fed$w_county <- as.numeric(substr(jobs_fed$w_geocode_tract, 3, 5)) #gets rid of leading 0
jobs_fed$w_tract <- as.numeric(substr(jobs_fed$w_geocode_tract, 6, 11))

jobs_priv$w_state <- as.numeric(substr(jobs_priv$w_geocode_tract, 1, 2))
jobs_priv$w_county <- as.numeric(substr(jobs_priv$w_geocode_tract, 3, 5)) #gets rid of leading 0
jobs_priv$w_tract <- as.numeric(substr(jobs_priv$w_geocode_tract, 6, 11))

```

What % of jobs flow from outside of Fairfax County?
```{r}
# for jobs all (059 is Fairfax code)
bool_cond <-jobs_all$r_county != 59 & jobs_all$w_county == 59#this means all jobs where residence is outside of                                                             # Fairfax but workplace is in Fairfax
pie(c(mean(bool_cond) * 100, (1 - mean(bool_cond)) * 100), labels = c("% Jobs in Fairfax flowing from outside", "% Jobs in Fairfax flowing from within"))
```

Of the flows into Fairfax County from outside, what percent are from other counties in Virginia?
```{r}
perc_flows_VA <- c(mean(jobs_all[bool_cond, ]$r_state == 51) *100, (1 - mean(jobs_all[bool_cond, ]$r_state == 51)) *100)
perc_flows_VA

agg <- jobs_all[jobs_all[bool_cond, ]$r_state == 51, ] %>%
  group_by(r_county) %>%
  summarise(S000 = sum(S000))

trimmed <- agg[order(-agg$S000), ][1:10, ]

ggplot(trimmed, aes(factor(r_county), S000)) + geom_col() + coord_flip()
```


